#
# Copy package files under packages/ and ros2_ws.tar.gz to the current directory before running this script.
#

################################################################################
# base system
################################################################################

FROM rosmed/docker-ubuntu-vnc-desktop-base:ismr2025 as system

#
# Copy 3D Silcer
#

WORKDIR /root
RUN mkdir -p /root/slicer/packages

#
# Additional ROS2 packages (dVRK) + ros2 workspace
#
WORKDIR /root
RUN apt update \
    && apt install -y python3-vcstool python3-colcon-common-extensions \
    && apt install -y python3-pykdl \
    && apt install -y libxml2-dev libraw1394-dev libncurses5-dev qtcreator \
    && apt install -y swig sox espeak cmake-curses-gui cmake-qt-gui git \
    && apt install -y subversion gfortran libcppunit-dev libqt5xmlpatterns5-dev libbluetooth-dev \
    && apt install -y ros-jazzy-joint-state-publisher* ros-jazzy-xacro \
    && apt install -y ros-jazzy-object-recognition-msgs ros-jazzy-moveit

RUN apt-get update \
    && apt-get install -y libxcursor-dev \
    && apt-get install -y libxinerama-dev \
    && apt-get install -y libasound2-dev libgl1-mesa-dev xorg-dev \
    && apt-get install -y libusb-1.0.0-dev

#COPY ros2_ws.tar.gz /root/
#RUN cd /root \
#    && tar zxvf ros2_ws.tar.gz \
#    && rm ros2_ws.tar.gz

#
# Install 3D Slicer and Extensions
#
#RUN /bin/bash -c 'ls /root/slicer/packages/*-linux-amd64-*.tar.gz |xargs -n1 -I{} tar -xzf {} -C /root/slicer ' \
#    && /bin/bash -c 'rm `find /root/slicer/packages/*-linux-amd64-*.tar.gz`' \
#    && /bin/bash -c 'find /root/slicer/*-linux-amd64-* -maxdepth 0|xargs -n1 -I{} mv {} /root/slicer/Slicer-5.8'
#RUN /bin/bash -c 'ls /root/slicer/packages/*-linux-amd64-SlicerROS2*.tar.gz |xargs -n1 -I{} tar -xzf {} -C /root/slicer ' \
#    && /bin/bash -c 'rm `find /root/slicer/packages/*-linux-amd64-SlicerROS2*.tar.gz`' \
#    && /bin/bash -c 'find /root/slicer/*-linux-amd64-SlicerROS2* -maxdepth 0|xargs -n1 -I{} mv {} /root/slicer/Slicer-5.8'

COPY Slicer-5.8 /root/slicer/Slicer-5.8

COPY packages/* /root/slicer/packages
COPY slicer/install-extension.py /root/slicer
COPY slicer/install-module.py /root/slicer
COPY slicer/start-slicer-ros2.bash /root
COPY slicer/install-segmentation-unet.bash /root
WORKDIR /root
RUN cd /root \
    && chmod 755 start-slicer-ros2.bash \
    && chmod 755 install-segmentation-unet.bash

RUN /bin/bash -c "export EXTENSION_DIR=/root/slicer/packages; xvfb-run --auto-servernum /root/slicer/Slicer-5.8/Slicer --no-main-window --no-splash --python-script /root/slicer/install-extension.py" \


#
# Install 3D Slicer Modules
#

# SlicerROS2
WORKING /root
RUN /bin/bash -c "export MODULE_DIR=/root/ros2_ws/build/ROS2/lib/Slicer-5.8/qt-loadable-modules; xvfb-run --auto-servernum /root/slicer/Slicer-5.8/Slicer --no-main-window --no-splash --python-script /root/slicer/install-module.py"

# Trajectory Tracing
WORKDIR /root
RUN mkdir -p /root/slicer/modules \
    && cd /root/slicer/modules \
    && git clone https://github.com/rosmed/robot_trajectory_trace_SlicerROS2 \
    && /bin/bash -c "export MODULE_DIR=/root/slicer/modules/robot_trajectory_trace_SlicerROS2/TrajectoryGenerator/RobotTrajectoryGenerator; xvfb-run --auto-servernum /root/slicer/Slicer-5.8/Slicer --no-main-window --no-splash --python-script /root/slicer/install-module.py"

# AI-based Ultrasound Segmentation
# This must be the last, because the module requires user interaction at the first launch.
WORKDIR /root
RUN mkdir -p /root/slicer/modules \
    && cd /root/slicer/modules \
    && mkdir aigt \
    && cd aigt \
    && git init \
    && git config core.sparsecheckout true \
    && echo 'SlicerExtension/LiveUltrasoundAi/SegmentationUNet*' > .git/info/sparse-checkout \
    && git remote add -f origin https://github.com/SlicerIGT/aigt \
    && git pull origin master
#    && /bin/bash -c "export MODULE_DIR=/root/slicer/modules/aigt/SlicerExtension/LiveUltrasoundAi/SegmentationUNet; xvfb-run --auto-servernum /root/slicer/Slicer-5.8/Slicer --no-main-window --no-splash --python-script /root/slicer/install-module.py"

WORKDIR /root
RUN mkdir -p ambf_ws \
    && cd ambf_ws \
    && mkdir -p src \
    && cd src \
    && git clone https://github.com/LauraConnolly/ambf \
    && cd ambf \
    && git checkout ros2-support \
    && cd /root/ambf_ws \
    && /bin/bash -c 'source /opt/ros/jazzy/setup.sh; colcon build'

# ISMR Tutorial Data
WORKDIR /root
RUN cd /root \
    && git clone https://github.com/rosmed/ismr2025
