################################################################################
# 3D Slicer for ISMR 2021 Tutorial
################################################################################

#FROM ros:galactic-ros-base as system
FROM rosmed/docker-ubuntu-vnc-desktop-base:ismr2025 AS system


WORKDIR /root

#
# Build 3D Slicer
#
RUN mkdir /root/slicer \
    && cd /root/slicer \
    && git clone --branch v5.8.1 https://github.com/slicer/Slicer \
    && mkdir Slicer-SuperBuild-Release \
    && cd Slicer-SuperBuild-Release \
    && cmake -DCMAKE_BUILD_TYPE:STRING=Release -DSlicer_USE_SYSTEM_OpenSSL=ON ../Slicer \
    && make -j4

